### PR TITLE
Add float arrays

### PR DESCRIPTION
**Pull request by dsmyth**
Here's my first cut: deserializes double precision 1d arrays into Vector<Float64>

Haven't looked at generalizing per your comments yet
Haven't looked at serializing yet.

### CODE REVIEW

**Comment by lganzzzo** [comment]
Nice!
I'll try to generalize this

**Comment by lganzzzo** [comment]
Hey @dsmyth ,

Please find my PR with improvements https://github.com/dsmyth/oatpp-postgresql/pull/1

**Comment by dsmyth** [comment]
I have merged your generalized implementation of deserializeArray2 and cleaned up the old code. I have my gcc warnings cranked up to max, so moved the include for inet.h to the header file.

**Comment by lganzzzo** [comment]
Nice!

I'm currently looking into multidimensional arrays support.

Apart from that, I was thinking about the struct PgArray structures -
while it's good for now... I'm not sure if it's a portable solution. 
Theoretically, there is no guaranty that those structures will be "packed" on all platforms.
If the compiler introduces additional padding it won't work.
I think at some point we'll have to refactor that to value-by-value reads from the data.

**Comment by dsmyth** [comment]
You may want to have a look at https://github.com/pgagarinov/libpqtypes -- rather old but probably still relevant.

**Comment by lganzzzo** [comment]
Hey @dsmyth ,

Please find a new PR - [multidimensional array deserialization](https://github.com/dsmyth/oatpp-postgresql/pull/2)

**Pull request merged**
